SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

PLAYER_1 = [1, (SCREEN_WIDTH / 2, 25)]
PLAYER_2 = [2, (SCREEN_WIDTH / 2, SCREEN_HEIGHT - 15)]
PLAYER_SPEED = 4
BALL_SPEED = 3
TOP = -BALL_SPEED
LEFT = -BALL_SPEED
BOTTOM = BALL_SPEED
RIGHT = BALL_SPEED
CENTER = 0